### PR TITLE
[feature] update with changes on imgui 1.9x

### PR DESCRIPTION
**Pull request by mikecovlee**

### CODE REVIEW

**Comment by ice1000** [comment]
> @mikecovlee
[make it works on glfw](https://github.com/covscript/covscript-imgui/pull/4/commits/d6a85b67fd7ebf9119a55607105e5b4674414f6b)

make it work, not works

**Comment by mikecovlee** [comment]
> > @mikecovlee
> > [make it works on glfw](https://github.com/covscript/covscript-imgui/pull/4/commits/d6a85b67fd7ebf9119a55607105e5b4674414f6b)
> 
> make it work, not works

I'm on a trip now, only tested these codes on macOS, so I labeled this pr with [WIP]. I will continue work with this pr after come back to home.

**Comment by mikecovlee** [comment]
> > @mikecovlee
> > [make it works on glfw](https://github.com/covscript/covscript-imgui/pull/4/commits/d6a85b67fd7ebf9119a55607105e5b4674414f6b)
> 
> make it work, not works

I have tested this pr in both windows and macOS, haven't found any problem.

**Review by ice1000 — COMMENTED** [review]
I was just pointing out a grammar error in the commit message

**Comment by mikecovlee** [comment]
> I was just pointing out a grammar error in the commit message

fine.

**Pull request merged**
